# --ESTRUTURA DE REPETIÇÃO COM TESTE LÓGICO (WHILE)
# WHILE SERVE PARA FAZER ESTRUTURA DE REPETIÇÃO QUANDO NÃO SE SABE SEU FIM
# É UM ÓTIMO SUBSTITUTO DO FOR
# DENTRO DO WHILE TBM CABE CONDIÇÕES E REPETIÇÕES
