frase = 'Curso em Vídeo Python'
print(frase)
print(frase[1:5])
print(frase[:14])
print(frase[15:])
print(frase[::2])
print(frase.upper().count('O')) #jogou tudo pra maiusculo e depois contou quantas tinha
print(frase.upper().find('EM'))
print(len(frase))
print(frase)
frase = frase.replace('Python', 'Android')
print(frase)
print('Vídeo' in frase)
print('Python' in frase)
frase = frase.replace('Android', 'Python')
print(frase)
print('Python' in frase)
print(frase.find('python'))
print(frase.lower().find('python'))
print(frase.split())
dividido = frase.split()
print(dividido)
print(dividido[2])
print(' * '.join(dividido))
print(dividido[2][3])
print(dividido[3][1])
