w = int(input('Digite um número para ver sua tabuada: '))
print('-' *12)
# quando usar {} no lugar do multiplicador, botar o :2 dentro das chaves >> {:2} para alinhas o =
print('{} x  0 = {}'.format(w, w * 0))
print('{} x  1 = {}'.format(w, w * 1))
print('{} x  2 = {}'.format(w, w * 2))
print('{} x  3 = {}'.format(w, w * 3))
print('{} x  4 = {}'.format(w, w * 4))
print('{} x  5 = {}'.format(w, w * 5))
print('{} x  6 = {}'.format(w, w * 6))
print('{} x  7 = {}'.format(w, w * 7))
print('{} x  8 = {}'.format(w, w * 8))
print('{} x  9 = {}'.format(w, w * 9))
print('{} x 10 = {}'.format(w, w * 10))
print('-'*12)
